-- ============================================================================
-- FASHIONest Product Catalog Seed Data
-- Run this in Supabase SQL Editor to populate the products table
-- ============================================================================

INSERT INTO products (product_id, title, description, category, subcategory, price, fabric, color, occasion, rating, image_url, stock) VALUES
-- SAREES: Kanchipuram (6)
('SAR-KAN-001', 'Temple Border Kanchipuram Silk Saree', 'Temple Border kanchipuram silk saree crafted in pure silk for wedding styling and modern women''s ethnic wardrobes.', 'Sarees', 'Kanchipuram Sarees', 6290, 'Pure Silk', 'Ruby Red', 'Wedding', 4.1, 'https://source.unsplash.com/featured/900x1200/?kanchipuram+saree&sig=1', 11),
('SAR-KAN-002', 'Heritage Kanchipuram Silk Saree', 'Heritage kanchipuram silk saree crafted in pure silk for wedding styling and modern women''s ethnic wardrobes.', 'Sarees', 'Kanchipuram Sarees', 6550, 'Pure Silk', 'Peacock Blue', 'Wedding', 4.3, 'https://source.unsplash.com/featured/900x1200/?kanchipuram+saree&sig=2', 14),
('SAR-KAN-003', 'Bridal Kanchipuram Silk Saree', 'Bridal kanchipuram silk saree crafted in pure silk for wedding styling and modern women''s ethnic wardrobes.', 'Sarees', 'Kanchipuram Sarees', 6810, 'Pure Silk', 'Emerald Green', 'Wedding', 4.5, 'https://source.unsplash.com/featured/900x1200/?kanchipuram+saree&sig=3', 17),
('SAR-KAN-004', 'Zari Weave Kanchipuram Silk Saree', 'Zari Weave kanchipuram silk saree crafted in pure silk for wedding styling and modern women''s ethnic wardrobes.', 'Sarees', 'Kanchipuram Sarees', 7070, 'Pure Silk', 'Deep Maroon', 'Wedding', 4.6, 'https://source.unsplash.com/featured/900x1200/?kanchipuram+saree&sig=4', 20),
('SAR-KAN-005', 'Festive Kanchipuram Silk Saree', 'Festive kanchipuram silk saree crafted in pure silk for wedding styling and modern women''s ethnic wardrobes.', 'Sarees', 'Kanchipuram Sarees', 7330, 'Pure Silk', 'Sun Gold', 'Wedding', 4.8, 'https://source.unsplash.com/featured/900x1200/?kanchipuram+saree&sig=5', 23),
('SAR-KAN-006', 'Handloom Kanchipuram Silk Saree', 'Handloom kanchipuram silk saree crafted in pure silk for wedding styling and modern women''s ethnic wardrobes.', 'Sarees', 'Kanchipuram Sarees', 7590, 'Pure Silk', 'Royal Purple', 'Wedding', 4.1, 'https://source.unsplash.com/featured/900x1200/?kanchipuram+saree&sig=6', 26),

-- SAREES: Banarasi (6)
('SAR-BAN-007', 'Classic Banarasi Silk Saree', 'Classic banarasi silk saree crafted in silk blend for festive styling.', 'Sarees', 'Banarasi Sarees', 5490, 'Silk Blend', 'Sun Gold', 'Festive', 4.3, 'https://source.unsplash.com/featured/900x1200/?banarasi+saree&sig=7', 29),
('SAR-BAN-008', 'Rani Pink Banarasi Silk Saree', 'Rani Pink banarasi silk saree crafted in silk blend for festive styling.', 'Sarees', 'Banarasi Sarees', 5730, 'Silk Blend', 'Wine', 'Festive', 4.5, 'https://source.unsplash.com/featured/900x1200/?banarasi+saree&sig=8', 32),
('SAR-BAN-009', 'Wedding Banarasi Silk Saree', 'Wedding banarasi silk saree crafted in silk blend for festive styling.', 'Sarees', 'Banarasi Sarees', 5970, 'Silk Blend', 'Magenta', 'Festive', 4.6, 'https://source.unsplash.com/featured/900x1200/?banarasi+saree&sig=9', 8),
('SAR-BAN-010', 'Brocade Banarasi Silk Saree', 'Brocade banarasi silk saree crafted in silk blend for festive styling.', 'Sarees', 'Banarasi Sarees', 6210, 'Silk Blend', 'Midnight Blue', 'Festive', 4.8, 'https://source.unsplash.com/featured/900x1200/?banarasi+saree&sig=10', 11),
('SAR-BAN-011', 'Heritage Banarasi Silk Saree', 'Heritage banarasi silk saree crafted in silk blend for festive styling.', 'Sarees', 'Banarasi Sarees', 6450, 'Silk Blend', 'Bottle Green', 'Festive', 4.1, 'https://source.unsplash.com/featured/900x1200/?banarasi+saree&sig=11', 14),
('SAR-BAN-012', 'Occasion Banarasi Silk Saree', 'Occasion banarasi silk saree crafted in silk blend for festive styling.', 'Sarees', 'Banarasi Sarees', 6690, 'Silk Blend', 'Rose Pink', 'Festive', 4.3, 'https://source.unsplash.com/featured/900x1200/?banarasi+saree&sig=12', 17),

-- SAREES: Linen (6)
('SAR-LIN-013', 'Breezy Linen Saree', 'Breezy linen saree crafted in linen for daily wear styling.', 'Sarees', 'Linen Sarees', 2490, 'Linen', 'Mint Green', 'Daily Wear', 4.5, 'https://source.unsplash.com/featured/900x1200/?linen+saree&sig=13', 20),
('SAR-LIN-014', 'Printed Linen Saree', 'Printed linen saree crafted in linen for daily wear styling.', 'Sarees', 'Linen Sarees', 2670, 'Linen', 'Powder Blue', 'Daily Wear', 4.6, 'https://source.unsplash.com/featured/900x1200/?linen+saree&sig=14', 23),
('SAR-LIN-015', 'Workday Linen Saree', 'Workday linen saree crafted in linen for daily wear styling.', 'Sarees', 'Linen Sarees', 2850, 'Linen', 'Beige', 'Daily Wear', 4.8, 'https://source.unsplash.com/featured/900x1200/?linen+saree&sig=15', 26),
('SAR-LIN-016', 'Soft Drape Linen Saree', 'Soft Drape linen saree crafted in linen for daily wear styling.', 'Sarees', 'Linen Sarees', 3030, 'Linen', 'Lavender', 'Daily Wear', 4.1, 'https://source.unsplash.com/featured/900x1200/?linen+saree&sig=16', 29),
('SAR-LIN-017', 'Minimal Linen Saree', 'Minimal linen saree crafted in linen for daily wear styling.', 'Sarees', 'Linen Sarees', 3210, 'Linen', 'Ivory', 'Daily Wear', 4.3, 'https://source.unsplash.com/featured/900x1200/?linen+saree&sig=17', 32),
('SAR-LIN-018', 'Everyday Linen Saree', 'Everyday linen saree crafted in linen for daily wear styling.', 'Sarees', 'Linen Sarees', 3390, 'Linen', 'Stone Grey', 'Daily Wear', 4.5, 'https://source.unsplash.com/featured/900x1200/?linen+saree&sig=18', 8),

-- SAREES: Organza (6)
('SAR-ORG-019', 'Floral Organza Saree', 'Floral organza saree crafted in organza for party styling.', 'Sarees', 'Organza Sarees', 3390, 'Organza', 'Blush Pink', 'Party', 4.6, 'https://source.unsplash.com/featured/900x1200/?organza+saree&sig=19', 11),
('SAR-ORG-020', 'Evening Organza Saree', 'Evening organza saree crafted in organza for party styling.', 'Sarees', 'Organza Sarees', 3600, 'Organza', 'Champagne', 'Party', 4.8, 'https://source.unsplash.com/featured/900x1200/?organza+saree&sig=20', 14),
('SAR-ORG-021', 'Statement Organza Saree', 'Statement organza saree crafted in organza for party styling.', 'Sarees', 'Organza Sarees', 3810, 'Organza', 'Lilac', 'Party', 4.1, 'https://source.unsplash.com/featured/900x1200/?organza+saree&sig=21', 17),
('SAR-ORG-022', 'Sheer Organza Saree', 'Sheer organza saree crafted in organza for party styling.', 'Sarees', 'Organza Sarees', 4020, 'Organza', 'Coral', 'Party', 4.3, 'https://source.unsplash.com/featured/900x1200/?organza+saree&sig=22', 20),
('SAR-ORG-023', 'Pearl Organza Saree', 'Pearl organza saree crafted in organza for party styling.', 'Sarees', 'Organza Sarees', 4230, 'Organza', 'Dusty Rose', 'Party', 4.5, 'https://source.unsplash.com/featured/900x1200/?organza+saree&sig=23', 23),
('SAR-ORG-024', 'Embellished Organza Saree', 'Embellished organza saree crafted in organza for party styling.', 'Sarees', 'Organza Sarees', 4440, 'Organza', 'Ice Blue', 'Party', 4.6, 'https://source.unsplash.com/featured/900x1200/?organza+saree&sig=24', 26),

-- SAREES: Cotton (6)
('SAR-COT-025', 'Classic Cotton Saree', 'Classic cotton saree crafted in cotton for office styling.', 'Sarees', 'Cotton Sarees', 1990, 'Cotton', 'Sky Blue', 'Office', 4.8, 'https://source.unsplash.com/featured/900x1200/?cotton+saree&sig=25', 29),
('SAR-COT-026', 'Handloom Cotton Saree', 'Handloom cotton saree crafted in cotton for office styling.', 'Sarees', 'Cotton Sarees', 2140, 'Cotton', 'Mustard', 'Office', 4.1, 'https://source.unsplash.com/featured/900x1200/?cotton+saree&sig=26', 32),
('SAR-COT-027', 'Temple Border Cotton Saree', 'Temple Border cotton saree crafted in cotton for office styling.', 'Sarees', 'Cotton Sarees', 2290, 'Cotton', 'Teal', 'Office', 4.3, 'https://source.unsplash.com/featured/900x1200/?cotton+saree&sig=27', 8),
('SAR-COT-028', 'Soft Weave Cotton Saree', 'Soft Weave cotton saree crafted in cotton for office styling.', 'Sarees', 'Cotton Sarees', 2440, 'Cotton', 'Brick Red', 'Office', 4.5, 'https://source.unsplash.com/featured/900x1200/?cotton+saree&sig=28', 11),
('SAR-COT-029', 'Daily Edit Cotton Saree', 'Daily Edit cotton saree crafted in cotton for office styling.', 'Sarees', 'Cotton Sarees', 2590, 'Cotton', 'Olive', 'Office', 4.6, 'https://source.unsplash.com/featured/900x1200/?cotton+saree&sig=29', 14),
('SAR-COT-030', 'Printed Cotton Saree', 'Printed cotton saree crafted in cotton for office styling.', 'Sarees', 'Cotton Sarees', 2740, 'Cotton', 'Off White', 'Office', 4.8, 'https://source.unsplash.com/featured/900x1200/?cotton+saree&sig=30', 17),

-- KURTAS: Anarkali (6)
('KUR-ANK-031', 'Mirror Work Anarkali Kurta', 'Mirror Work anarkali kurta crafted in rayon for festive styling.', 'Kurtas', 'Anarkali Kurtas', 2390, 'Rayon', 'Maroon', 'Festive', 4.1, 'https://source.unsplash.com/featured/900x1200/?anarkali+kurta&sig=31', 20),
('KUR-ANK-032', 'Festive Anarkali Kurta', 'Festive anarkali kurta crafted in rayon for festive styling.', 'Kurtas', 'Anarkali Kurtas', 2550, 'Rayon', 'Bottle Green', 'Festive', 4.3, 'https://source.unsplash.com/featured/900x1200/?anarkali+kurta&sig=32', 23),
('KUR-ANK-033', 'Flared Anarkali Kurta', 'Flared anarkali kurta crafted in rayon for festive styling.', 'Kurtas', 'Anarkali Kurtas', 2710, 'Rayon', 'Royal Blue', 'Festive', 4.5, 'https://source.unsplash.com/featured/900x1200/?anarkali+kurta&sig=33', 26),
('KUR-ANK-034', 'Embroidered Anarkali Kurta', 'Embroidered anarkali kurta crafted in rayon for festive styling.', 'Kurtas', 'Anarkali Kurtas', 2870, 'Rayon', 'Rust', 'Festive', 4.6, 'https://source.unsplash.com/featured/900x1200/?anarkali+kurta&sig=34', 29),
('KUR-ANK-035', 'Panelled Anarkali Kurta', 'Panelled anarkali kurta crafted in rayon for festive styling.', 'Kurtas', 'Anarkali Kurtas', 3030, 'Rayon', 'Wine', 'Festive', 4.8, 'https://source.unsplash.com/featured/900x1200/?anarkali+kurta&sig=35', 32),
('KUR-ANK-036', 'Occasion Anarkali Kurta', 'Occasion anarkali kurta crafted in rayon for festive styling.', 'Kurtas', 'Anarkali Kurtas', 3190, 'Rayon', 'Plum', 'Festive', 4.1, 'https://source.unsplash.com/featured/900x1200/?anarkali+kurta&sig=36', 8),

-- KURTAS: Straight (6)
('KUR-STR-037', 'Tailored Straight Kurta', 'Tailored straight kurta crafted in cotton for office styling.', 'Kurtas', 'Straight Kurtas', 1490, 'Cotton', 'Ivory', 'Office', 4.3, 'https://source.unsplash.com/featured/900x1200/?straight+kurta&sig=37', 11),
('KUR-STR-038', 'Pocket Straight Kurta', 'Pocket straight kurta crafted in cotton for office styling.', 'Kurtas', 'Straight Kurtas', 1630, 'Cotton', 'Sage', 'Office', 4.5, 'https://source.unsplash.com/featured/900x1200/?straight+kurta&sig=38', 14),
('KUR-STR-039', 'Everyday Straight Kurta', 'Everyday straight kurta crafted in cotton for office styling.', 'Kurtas', 'Straight Kurtas', 1770, 'Cotton', 'Navy', 'Office', 4.6, 'https://source.unsplash.com/featured/900x1200/?straight+kurta&sig=39', 17),
('KUR-STR-040', 'Minimal Straight Kurta', 'Minimal straight kurta crafted in cotton for office styling.', 'Kurtas', 'Straight Kurtas', 1910, 'Cotton', 'Rose Brown', 'Office', 4.8, 'https://source.unsplash.com/featured/900x1200/?straight+kurta&sig=40', 20),
('KUR-STR-041', 'Workwear Straight Kurta', 'Workwear straight kurta crafted in cotton for office styling.', 'Kurtas', 'Straight Kurtas', 2050, 'Cotton', 'Taupe', 'Office', 4.1, 'https://source.unsplash.com/featured/900x1200/?straight+kurta&sig=41', 23),
('KUR-STR-042', 'Clean Line Straight Kurta', 'Clean Line straight kurta crafted in cotton for office styling.', 'Kurtas', 'Straight Kurtas', 2190, 'Cotton', 'Black', 'Office', 4.3, 'https://source.unsplash.com/featured/900x1200/?straight+kurta&sig=42', 26),

-- KURTAS: Printed (6)
('KUR-PRT-043', 'Block Print Printed Kurta', 'Block Print printed kurta crafted in viscose for casual styling.', 'Kurtas', 'Printed Kurtas', 1590, 'Viscose', 'Indigo', 'Casual', 4.5, 'https://source.unsplash.com/featured/900x1200/?printed+kurta&sig=43', 29),
('KUR-PRT-044', 'Floral Printed Kurta', 'Floral printed kurta crafted in viscose for casual styling.', 'Kurtas', 'Printed Kurtas', 1725, 'Viscose', 'Terracotta', 'Casual', 4.6, 'https://source.unsplash.com/featured/900x1200/?printed+kurta&sig=44', 32),
('KUR-PRT-045', 'Indigo Printed Kurta', 'Indigo printed kurta crafted in viscose for casual styling.', 'Kurtas', 'Printed Kurtas', 1860, 'Viscose', 'Mustard', 'Casual', 4.8, 'https://source.unsplash.com/featured/900x1200/?printed+kurta&sig=45', 8),
('KUR-PRT-046', 'Weekend Printed Kurta', 'Weekend printed kurta crafted in viscose for casual styling.', 'Kurtas', 'Printed Kurtas', 1995, 'Viscose', 'Mint', 'Casual', 4.1, 'https://source.unsplash.com/featured/900x1200/?printed+kurta&sig=46', 11),
('KUR-PRT-047', 'Fusion Printed Kurta', 'Fusion printed kurta crafted in viscose for casual styling.', 'Kurtas', 'Printed Kurtas', 2130, 'Viscose', 'Berry', 'Casual', 4.3, 'https://source.unsplash.com/featured/900x1200/?printed+kurta&sig=47', 14),
('KUR-PRT-048', 'Garden Printed Kurta', 'Garden printed kurta crafted in viscose for casual styling.', 'Kurtas', 'Printed Kurtas', 2265, 'Viscose', 'Cream', 'Casual', 4.5, 'https://source.unsplash.com/featured/900x1200/?printed+kurta&sig=48', 17),

-- KURTAS: Embroidered (6)
('KUR-EMB-049', 'Threadwork Embroidered Kurta', 'Threadwork embroidered kurta crafted in chanderi blend for festive styling.', 'Kurtas', 'Embroidered Kurtas', 2190, 'Chanderi Blend', 'Rose Pink', 'Festive', 4.6, 'https://source.unsplash.com/featured/900x1200/?embroidered+kurta&sig=49', 20),
('KUR-EMB-050', 'Zari Accent Embroidered Kurta', 'Zari Accent embroidered kurta crafted in chanderi blend for festive styling.', 'Kurtas', 'Embroidered Kurtas', 2355, 'Chanderi Blend', 'Olive', 'Festive', 4.8, 'https://source.unsplash.com/featured/900x1200/?embroidered+kurta&sig=50', 23),
('KUR-EMB-051', 'Statement Embroidered Kurta', 'Statement embroidered kurta crafted in chanderi blend for festive styling.', 'Kurtas', 'Embroidered Kurtas', 2520, 'Chanderi Blend', 'Peach', 'Festive', 4.1, 'https://source.unsplash.com/featured/900x1200/?embroidered+kurta&sig=51', 26),
('KUR-EMB-052', 'Elegant Embroidered Kurta', 'Elegant embroidered kurta crafted in chanderi blend for festive styling.', 'Kurtas', 'Embroidered Kurtas', 2685, 'Chanderi Blend', 'Slate Blue', 'Festive', 4.3, 'https://source.unsplash.com/featured/900x1200/?embroidered+kurta&sig=52', 29),
('KUR-EMB-053', 'Festive Embroidered Kurta', 'Festive embroidered kurta crafted in chanderi blend for festive styling.', 'Kurtas', 'Embroidered Kurtas', 2850, 'Chanderi Blend', 'Sand', 'Festive', 4.5, 'https://source.unsplash.com/featured/900x1200/?embroidered+kurta&sig=53', 32),
('KUR-EMB-054', 'Heirloom Embroidered Kurta', 'Heirloom embroidered kurta crafted in chanderi blend for festive styling.', 'Kurtas', 'Embroidered Kurtas', 3015, 'Chanderi Blend', 'Crimson', 'Festive', 4.6, 'https://source.unsplash.com/featured/900x1200/?embroidered+kurta&sig=54', 8),

-- KURTAS: A-Line (6)
('KUR-ALN-055', 'Flowy A-Line Kurta', 'Flowy a-line kurta crafted in cotton blend for daily wear styling.', 'Kurtas', 'A-Line Kurtas', 1690, 'Cotton Blend', 'Lilac', 'Daily Wear', 4.8, 'https://source.unsplash.com/featured/900x1200/?aline+kurta&sig=55', 11),
('KUR-ALN-056', 'Modern A-Line Kurta', 'Modern a-line kurta crafted in cotton blend for daily wear styling.', 'Kurtas', 'A-Line Kurtas', 1835, 'Cotton Blend', 'Aqua', 'Daily Wear', 4.1, 'https://source.unsplash.com/featured/900x1200/?aline+kurta&sig=56', 14),
('KUR-ALN-057', 'Easy Fit A-Line Kurta', 'Easy Fit a-line kurta crafted in cotton blend for daily wear styling.', 'Kurtas', 'A-Line Kurtas', 1980, 'Cotton Blend', 'Mocha', 'Daily Wear', 4.3, 'https://source.unsplash.com/featured/900x1200/?aline+kurta&sig=57', 17),
('KUR-ALN-058', 'Soft Drape A-Line Kurta', 'Soft Drape a-line kurta crafted in cotton blend for daily wear styling.', 'Kurtas', 'A-Line Kurtas', 2125, 'Cotton Blend', 'Brick', 'Daily Wear', 4.5, 'https://source.unsplash.com/featured/900x1200/?aline+kurta&sig=58', 20),
('KUR-ALN-059', 'City Edit A-Line Kurta', 'City Edit a-line kurta crafted in cotton blend for daily wear styling.', 'Kurtas', 'A-Line Kurtas', 2270, 'Cotton Blend', 'Ivory', 'Daily Wear', 4.6, 'https://source.unsplash.com/featured/900x1200/?aline+kurta&sig=59', 23),
('KUR-ALN-060', 'Pleated A-Line Kurta', 'Pleated a-line kurta crafted in cotton blend for daily wear styling.', 'Kurtas', 'A-Line Kurtas', 2415, 'Cotton Blend', 'Forest Green', 'Daily Wear', 4.8, 'https://source.unsplash.com/featured/900x1200/?aline+kurta&sig=60', 26),

-- BLOUSES: Silk (6)
('BLO-SLK-061', 'Boat Neck Silk Blouse', 'Boat Neck silk blouse crafted in silk for wedding styling.', 'Blouses', 'Silk Blouses', 1490, 'Silk', 'Emerald', 'Wedding', 4.1, 'https://source.unsplash.com/featured/900x1200/?silk+blouse&sig=61', 29),
('BLO-SLK-062', 'Classic Silk Blouse', 'Classic silk blouse crafted in silk for wedding styling.', 'Blouses', 'Silk Blouses', 1610, 'Silk', 'Ruby', 'Wedding', 4.3, 'https://source.unsplash.com/featured/900x1200/?silk+blouse&sig=62', 32),
('BLO-SLK-063', 'Princess Cut Silk Blouse', 'Princess Cut silk blouse crafted in silk for wedding styling.', 'Blouses', 'Silk Blouses', 1730, 'Silk', 'Champagne', 'Wedding', 4.5, 'https://source.unsplash.com/featured/900x1200/?silk+blouse&sig=63', 8),
('BLO-SLK-064', 'Sleeveless Silk Blouse', 'Sleeveless silk blouse crafted in silk for wedding styling.', 'Blouses', 'Silk Blouses', 1850, 'Silk', 'Wine', 'Wedding', 4.6, 'https://source.unsplash.com/featured/900x1200/?silk+blouse&sig=64', 11),
('BLO-SLK-065', 'Elbow Sleeve Silk Blouse', 'Elbow Sleeve silk blouse crafted in silk for wedding styling.', 'Blouses', 'Silk Blouses', 1970, 'Silk', 'Royal Blue', 'Wedding', 4.8, 'https://source.unsplash.com/featured/900x1200/?silk+blouse&sig=65', 14),
('BLO-SLK-066', 'Festive Silk Blouse', 'Festive silk blouse crafted in silk for wedding styling.', 'Blouses', 'Silk Blouses', 2090, 'Silk', 'Copper', 'Wedding', 4.1, 'https://source.unsplash.com/featured/900x1200/?silk+blouse&sig=66', 17),

-- BLOUSES: Brocade (6)
('BLO-BRO-067', 'Embroidered Brocade Blouse', 'Embroidered brocade blouse crafted in brocade for festive styling.', 'Blouses', 'Brocade Blouses', 1690, 'Brocade', 'Gold', 'Festive', 4.3, 'https://source.unsplash.com/featured/900x1200/?brocade+blouse&sig=67', 20),
('BLO-BRO-068', 'Zari Detail Brocade Blouse', 'Zari Detail brocade blouse crafted in brocade for festive styling.', 'Blouses', 'Brocade Blouses', 1820, 'Brocade', 'Maroon', 'Festive', 4.5, 'https://source.unsplash.com/featured/900x1200/?brocade+blouse&sig=68', 23),
('BLO-BRO-069', 'Regal Brocade Blouse', 'Regal brocade blouse crafted in brocade for festive styling.', 'Blouses', 'Brocade Blouses', 1950, 'Brocade', 'Magenta', 'Festive', 4.6, 'https://source.unsplash.com/featured/900x1200/?brocade+blouse&sig=69', 26),
('BLO-BRO-070', 'Temple Border Brocade Blouse', 'Temple Border brocade blouse crafted in brocade for festive styling.', 'Blouses', 'Brocade Blouses', 2080, 'Brocade', 'Navy', 'Festive', 4.8, 'https://source.unsplash.com/featured/900x1200/?brocade+blouse&sig=70', 29),
('BLO-BRO-071', 'Statement Brocade Blouse', 'Statement brocade blouse crafted in brocade for festive styling.', 'Blouses', 'Brocade Blouses', 2210, 'Brocade', 'Olive', 'Festive', 4.1, 'https://source.unsplash.com/featured/900x1200/?brocade+blouse&sig=71', 32),
('BLO-BRO-072', 'Occasion Brocade Blouse', 'Occasion brocade blouse crafted in brocade for festive styling.', 'Blouses', 'Brocade Blouses', 2340, 'Brocade', 'Plum', 'Festive', 4.3, 'https://source.unsplash.com/featured/900x1200/?brocade+blouse&sig=72', 8),

-- BLOUSES: Cotton (6)
('BLO-COT-073', 'Printed Cotton Blouse', 'Printed cotton blouse crafted in cotton for daily wear styling.', 'Blouses', 'Cotton Blouses', 990, 'Cotton', 'Sky Blue', 'Daily Wear', 4.5, 'https://source.unsplash.com/featured/900x1200/?cotton+blouse&sig=73', 11),
('BLO-COT-074', 'Comfort Fit Cotton Blouse', 'Comfort Fit cotton blouse crafted in cotton for daily wear styling.', 'Blouses', 'Cotton Blouses', 1090, 'Cotton', 'Sand', 'Daily Wear', 4.6, 'https://source.unsplash.com/featured/900x1200/?cotton+blouse&sig=74', 14),
('BLO-COT-075', 'Soft Weave Cotton Blouse', 'Soft Weave cotton blouse crafted in cotton for daily wear styling.', 'Blouses', 'Cotton Blouses', 1190, 'Cotton', 'Ivory', 'Daily Wear', 4.8, 'https://source.unsplash.com/featured/900x1200/?cotton+blouse&sig=75', 17),
('BLO-COT-076', 'Everyday Cotton Blouse', 'Everyday cotton blouse crafted in cotton for daily wear styling.', 'Blouses', 'Cotton Blouses', 1290, 'Cotton', 'Black', 'Daily Wear', 4.1, 'https://source.unsplash.com/featured/900x1200/?cotton+blouse&sig=76', 20),
('BLO-COT-077', 'Tailored Cotton Blouse', 'Tailored cotton blouse crafted in cotton for daily wear styling.', 'Blouses', 'Cotton Blouses', 1390, 'Cotton', 'Coral', 'Daily Wear', 4.3, 'https://source.unsplash.com/featured/900x1200/?cotton+blouse&sig=77', 23),
('BLO-COT-078', 'Minimal Cotton Blouse', 'Minimal cotton blouse crafted in cotton for daily wear styling.', 'Blouses', 'Cotton Blouses', 1490, 'Cotton', 'Olive', 'Daily Wear', 4.5, 'https://source.unsplash.com/featured/900x1200/?cotton+blouse&sig=78', 26),

-- BLOUSES: Readymade (6)
('BLO-RMD-079', 'Padded Readymade Blouse', 'Padded readymade blouse crafted in silk blend for festive styling.', 'Blouses', 'Readymade Blouses', 1190, 'Silk Blend', 'Rose Gold', 'Festive', 4.6, 'https://source.unsplash.com/featured/900x1200/?readymade+blouse&sig=79', 29),
('BLO-RMD-080', 'Hook Back Readymade Blouse', 'Hook Back readymade blouse crafted in silk blend for festive styling.', 'Blouses', 'Readymade Blouses', 1300, 'Silk Blend', 'Teal', 'Festive', 4.8, 'https://source.unsplash.com/featured/900x1200/?readymade+blouse&sig=80', 32),
('BLO-RMD-081', 'Quick Fit Readymade Blouse', 'Quick Fit readymade blouse crafted in silk blend for festive styling.', 'Blouses', 'Readymade Blouses', 1410, 'Silk Blend', 'Rani Pink', 'Festive', 4.1, 'https://source.unsplash.com/featured/900x1200/?readymade+blouse&sig=81', 8),
('BLO-RMD-082', 'Ready Party Readymade Blouse', 'Ready Party readymade blouse crafted in silk blend for festive styling.', 'Blouses', 'Readymade Blouses', 1520, 'Silk Blend', 'Bottle Green', 'Festive', 4.3, 'https://source.unsplash.com/featured/900x1200/?readymade+blouse&sig=82', 11),
('BLO-RMD-083', 'Sculpted Readymade Blouse', 'Sculpted readymade blouse crafted in silk blend for festive styling.', 'Blouses', 'Readymade Blouses', 1630, 'Silk Blend', 'Copper', 'Festive', 4.5, 'https://source.unsplash.com/featured/900x1200/?readymade+blouse&sig=83', 14),
('BLO-RMD-084', 'Easy Wear Readymade Blouse', 'Easy Wear readymade blouse crafted in silk blend for festive styling.', 'Blouses', 'Readymade Blouses', 1740, 'Silk Blend', 'Pearl White', 'Festive', 4.6, 'https://source.unsplash.com/featured/900x1200/?readymade+blouse&sig=84', 17),

-- BLOUSES: Designer (6)
('BLO-DSG-085', 'Cutwork Designer Blouse', 'Cutwork designer blouse crafted in georgette blend for party styling.', 'Blouses', 'Designer Blouses', 1890, 'Georgette Blend', 'Black', 'Party', 4.8, 'https://source.unsplash.com/featured/900x1200/?designer+blouse&sig=85', 20),
('BLO-DSG-086', 'Mirror Detail Designer Blouse', 'Mirror Detail designer blouse crafted in georgette blend for party styling.', 'Blouses', 'Designer Blouses', 2030, 'Georgette Blend', 'Mauve', 'Party', 4.1, 'https://source.unsplash.com/featured/900x1200/?designer+blouse&sig=86', 23),
('BLO-DSG-087', 'Contemporary Designer Blouse', 'Contemporary designer blouse crafted in georgette blend for party styling.', 'Blouses', 'Designer Blouses', 2170, 'Georgette Blend', 'Silver', 'Party', 4.3, 'https://source.unsplash.com/featured/900x1200/?designer+blouse&sig=87', 26),
('BLO-DSG-088', 'Studio Edit Designer Blouse', 'Studio Edit designer blouse crafted in georgette blend for party styling.', 'Blouses', 'Designer Blouses', 2310, 'Georgette Blend', 'Cherry Red', 'Party', 4.5, 'https://source.unsplash.com/featured/900x1200/?designer+blouse&sig=88', 29),
('BLO-DSG-089', 'Fashion Designer Blouse', 'Fashion designer blouse crafted in georgette blend for party styling.', 'Blouses', 'Designer Blouses', 2450, 'Georgette Blend', 'Midnight Blue', 'Party', 4.6, 'https://source.unsplash.com/featured/900x1200/?designer+blouse&sig=89', 32),
('BLO-DSG-090', 'Evening Designer Blouse', 'Evening designer blouse crafted in georgette blend for party styling.', 'Blouses', 'Designer Blouses', 2590, 'Georgette Blend', 'Saffron', 'Party', 4.8, 'https://source.unsplash.com/featured/900x1200/?designer+blouse&sig=90', 8),

-- DRESSES: Ethnic Maxi (6)
('DRE-ETM-091', 'Flowy Ethnic Maxi Dress', 'Flowy ethnic maxi dress crafted in rayon blend for casual styling.', 'Dresses', 'Ethnic Maxi Dresses', 2290, 'Rayon Blend', 'Rose Pink', 'Casual', 4.1, 'https://source.unsplash.com/featured/900x1200/?ethnic+dress&sig=91', 11),
('DRE-ETM-092', 'Printed Ethnic Maxi Dress', 'Printed ethnic maxi dress crafted in rayon blend for casual styling.', 'Dresses', 'Ethnic Maxi Dresses', 2445, 'Rayon Blend', 'Indigo', 'Casual', 4.3, 'https://source.unsplash.com/featured/900x1200/?ethnic+dress&sig=92', 14),
('DRE-ETM-093', 'Gathered Ethnic Maxi Dress', 'Gathered ethnic maxi dress crafted in rayon blend for casual styling.', 'Dresses', 'Ethnic Maxi Dresses', 2600, 'Rayon Blend', 'Mustard', 'Casual', 4.5, 'https://source.unsplash.com/featured/900x1200/?ethnic+dress&sig=93', 17),
('DRE-ETM-094', 'Weekend Ethnic Maxi Dress', 'Weekend ethnic maxi dress crafted in rayon blend for casual styling.', 'Dresses', 'Ethnic Maxi Dresses', 2755, 'Rayon Blend', 'Ivory', 'Casual', 4.6, 'https://source.unsplash.com/featured/900x1200/?ethnic+dress&sig=94', 20),
('DRE-ETM-095', 'Easy Glam Ethnic Maxi Dress', 'Easy Glam ethnic maxi dress crafted in rayon blend for casual styling.', 'Dresses', 'Ethnic Maxi Dresses', 2910, 'Rayon Blend', 'Olive', 'Casual', 4.8, 'https://source.unsplash.com/featured/900x1200/?ethnic+dress&sig=95', 23),
('DRE-ETM-096', 'Garden Ethnic Maxi Dress', 'Garden ethnic maxi dress crafted in rayon blend for casual styling.', 'Dresses', 'Ethnic Maxi Dresses', 3065, 'Rayon Blend', 'Berry', 'Casual', 4.1, 'https://source.unsplash.com/featured/900x1200/?ethnic+dress&sig=96', 26),

-- DRESSES: Anarkali (6)
('DRE-ANA-097', 'Festive Anarkali Dress', 'Festive anarkali dress crafted in georgette for festive styling.', 'Dresses', 'Anarkali Dresses', 2890, 'Georgette', 'Maroon', 'Festive', 4.3, 'https://source.unsplash.com/featured/900x1200/?anarkali+dress&sig=97', 29),
('DRE-ANA-098', 'Panelled Anarkali Dress', 'Panelled anarkali dress crafted in georgette for festive styling.', 'Dresses', 'Anarkali Dresses', 3060, 'Georgette', 'Peach', 'Festive', 4.5, 'https://source.unsplash.com/featured/900x1200/?anarkali+dress&sig=98', 32),
('DRE-ANA-099', 'Twirl Anarkali Dress', 'Twirl anarkali dress crafted in georgette for festive styling.', 'Dresses', 'Anarkali Dresses', 3230, 'Georgette', 'Royal Blue', 'Festive', 4.6, 'https://source.unsplash.com/featured/900x1200/?anarkali+dress&sig=99', 8),
('DRE-ANA-100', 'Mirror Work Anarkali Dress', 'Mirror Work anarkali dress crafted in georgette for festive styling.', 'Dresses', 'Anarkali Dresses', 3400, 'Georgette', 'Bottle Green', 'Festive', 4.8, 'https://source.unsplash.com/featured/900x1200/?anarkali+dress&sig=100', 11),
('DRE-ANA-101', 'Occasion Anarkali Dress', 'Occasion anarkali dress crafted in georgette for festive styling.', 'Dresses', 'Anarkali Dresses', 3570, 'Georgette', 'Wine', 'Festive', 4.1, 'https://source.unsplash.com/featured/900x1200/?anarkali+dress&sig=101', 14),
('DRE-ANA-102', 'Graceful Anarkali Dress', 'Graceful anarkali dress crafted in georgette for festive styling.', 'Dresses', 'Anarkali Dresses', 3740, 'Georgette', 'Mauve', 'Festive', 4.3, 'https://source.unsplash.com/featured/900x1200/?anarkali+dress&sig=102', 17),

-- DRESSES: Festive (6)
('DRE-FES-103', 'Shimmer Festive Dress', 'Shimmer festive dress crafted in silk blend for party styling.', 'Dresses', 'Festive Dresses', 3190, 'Silk Blend', 'Gold', 'Party', 4.5, 'https://source.unsplash.com/featured/900x1200/?festive+dress&sig=103', 20),
('DRE-FES-104', 'Embellished Festive Dress', 'Embellished festive dress crafted in silk blend for party styling.', 'Dresses', 'Festive Dresses', 3370, 'Silk Blend', 'Rose Gold', 'Party', 4.6, 'https://source.unsplash.com/featured/900x1200/?festive+dress&sig=104', 23),
('DRE-FES-105', 'Evening Festive Dress', 'Evening festive dress crafted in silk blend for party styling.', 'Dresses', 'Festive Dresses', 3550, 'Silk Blend', 'Plum', 'Party', 4.8, 'https://source.unsplash.com/featured/900x1200/?festive+dress&sig=105', 26),
('DRE-FES-106', 'Celebration Festive Dress', 'Celebration festive dress crafted in silk blend for party styling.', 'Dresses', 'Festive Dresses', 3730, 'Silk Blend', 'Teal', 'Party', 4.1, 'https://source.unsplash.com/featured/900x1200/?festive+dress&sig=106', 29),
('DRE-FES-107', 'Classic Festive Dress', 'Classic festive dress crafted in silk blend for party styling.', 'Dresses', 'Festive Dresses', 3910, 'Silk Blend', 'Crimson', 'Party', 4.3, 'https://source.unsplash.com/featured/900x1200/?festive+dress&sig=107', 32),
('DRE-FES-108', 'Statement Festive Dress', 'Statement festive dress crafted in silk blend for party styling.', 'Dresses', 'Festive Dresses', 4090, 'Silk Blend', 'Silver', 'Party', 4.5, 'https://source.unsplash.com/featured/900x1200/?festive+dress&sig=108', 8),

-- DRESSES: Printed (6)
('DRE-PRT-109', 'Floral Printed Dress', 'Floral printed dress crafted in cotton blend for daily wear styling.', 'Dresses', 'Printed Dresses', 1890, 'Cotton Blend', 'Mint', 'Daily Wear', 4.6, 'https://source.unsplash.com/featured/900x1200/?printed+ethnic+dress&sig=109', 11),
('DRE-PRT-110', 'Block Print Printed Dress', 'Block Print printed dress crafted in cotton blend for daily wear styling.', 'Dresses', 'Printed Dresses', 2020, 'Cotton Blend', 'Sky Blue', 'Daily Wear', 4.8, 'https://source.unsplash.com/featured/900x1200/?printed+ethnic+dress&sig=110', 14),
('DRE-PRT-111', 'Soft Drape Printed Dress', 'Soft Drape printed dress crafted in cotton blend for daily wear styling.', 'Dresses', 'Printed Dresses', 2150, 'Cotton Blend', 'Terracotta', 'Daily Wear', 4.1, 'https://source.unsplash.com/featured/900x1200/?printed+ethnic+dress&sig=111', 17),
('DRE-PRT-112', 'Everyday Printed Dress', 'Everyday printed dress crafted in cotton blend for daily wear styling.', 'Dresses', 'Printed Dresses', 2280, 'Cotton Blend', 'Lemon', 'Daily Wear', 4.3, 'https://source.unsplash.com/featured/900x1200/?printed+ethnic+dress&sig=112', 20),
('DRE-PRT-113', 'Day Out Printed Dress', 'Day Out printed dress crafted in cotton blend for daily wear styling.', 'Dresses', 'Printed Dresses', 2410, 'Cotton Blend', 'Sage', 'Daily Wear', 4.5, 'https://source.unsplash.com/featured/900x1200/?printed+ethnic+dress&sig=113', 23),
('DRE-PRT-114', 'Minimal Printed Dress', 'Minimal printed dress crafted in cotton blend for daily wear styling.', 'Dresses', 'Printed Dresses', 2540, 'Cotton Blend', 'Blush', 'Daily Wear', 4.6, 'https://source.unsplash.com/featured/900x1200/?printed+ethnic+dress&sig=114', 26),

-- DRESSES: Indo-Western (6)
('DRE-IND-115', 'Contemporary Indo-Western Dress', 'Contemporary indo-western dress crafted in crepe for party styling.', 'Dresses', 'Indo-Western Dresses', 2690, 'Crepe', 'Black', 'Party', 4.8, 'https://source.unsplash.com/featured/900x1200/?indo+western+dress&sig=115', 29),
('DRE-IND-116', 'Cape Detail Indo-Western Dress', 'Cape Detail indo-western dress crafted in crepe for party styling.', 'Dresses', 'Indo-Western Dresses', 2855, 'Crepe', 'Champagne', 'Party', 4.1, 'https://source.unsplash.com/featured/900x1200/?indo+western+dress&sig=116', 32),
('DRE-IND-117', 'Layered Indo-Western Dress', 'Layered indo-western dress crafted in crepe for party styling.', 'Dresses', 'Indo-Western Dresses', 3020, 'Crepe', 'Rust', 'Party', 4.3, 'https://source.unsplash.com/featured/900x1200/?indo+western+dress&sig=117', 8),
('DRE-IND-118', 'Fusion Indo-Western Dress', 'Fusion indo-western dress crafted in crepe for party styling.', 'Dresses', 'Indo-Western Dresses', 3185, 'Crepe', 'Emerald', 'Party', 4.5, 'https://source.unsplash.com/featured/900x1200/?indo+western+dress&sig=118', 11),
('DRE-IND-119', 'Cocktail Indo-Western Dress', 'Cocktail indo-western dress crafted in crepe for party styling.', 'Dresses', 'Indo-Western Dresses', 3350, 'Crepe', 'Navy', 'Party', 4.6, 'https://source.unsplash.com/featured/900x1200/?indo+western+dress&sig=119', 14),
('DRE-IND-120', 'Modern Indo-Western Dress', 'Modern indo-western dress crafted in crepe for party styling.', 'Dresses', 'Indo-Western Dresses', 3515, 'Crepe', 'Lilac', 'Party', 4.8, 'https://source.unsplash.com/featured/900x1200/?indo+western+dress&sig=120', 17),

-- KURTA SETS: Cotton (6)
('KST-COT-121', 'Everyday Cotton Kurta Set', 'Everyday cotton kurta set crafted in cotton for daily wear styling.', 'Kurta Sets', 'Cotton Kurta Sets', 2390, 'Cotton', 'Ivory', 'Daily Wear', 4.1, 'https://source.unsplash.com/featured/900x1200/?kurta+set&sig=121', 20),
('KST-COT-122', 'Pocket Cotton Kurta Set', 'Pocket cotton kurta set crafted in cotton for daily wear styling.', 'Kurta Sets', 'Cotton Kurta Sets', 2540, 'Cotton', 'Sage', 'Daily Wear', 4.3, 'https://source.unsplash.com/featured/900x1200/?kurta+set&sig=122', 23),
('KST-COT-123', 'Soft Weave Cotton Kurta Set', 'Soft Weave cotton kurta set crafted in cotton for daily wear styling.', 'Kurta Sets', 'Cotton Kurta Sets', 2690, 'Cotton', 'Dusty Blue', 'Daily Wear', 4.5, 'https://source.unsplash.com/featured/900x1200/?kurta+set&sig=123', 26),
('KST-COT-124', 'Minimal Cotton Kurta Set', 'Minimal cotton kurta set crafted in cotton for daily wear styling.', 'Kurta Sets', 'Cotton Kurta Sets', 2840, 'Cotton', 'Mocha', 'Daily Wear', 4.6, 'https://source.unsplash.com/featured/900x1200/?kurta+set&sig=124', 29),
('KST-COT-125', 'Workday Cotton Kurta Set', 'Workday cotton kurta set crafted in cotton for daily wear styling.', 'Kurta Sets', 'Cotton Kurta Sets', 2990, 'Cotton', 'Brick', 'Daily Wear', 4.8, 'https://source.unsplash.com/featured/900x1200/?kurta+set&sig=125', 32),
('KST-COT-126', 'Comfort Cotton Kurta Set', 'Comfort cotton kurta set crafted in cotton for daily wear styling.', 'Kurta Sets', 'Cotton Kurta Sets', 3140, 'Cotton', 'Mustard', 'Daily Wear', 4.1, 'https://source.unsplash.com/featured/900x1200/?kurta+set&sig=126', 8),

-- KURTA SETS: Festive (6)
('KST-FES-127', 'Mirror Work Festive Kurta Set', 'Mirror Work festive kurta set crafted in silk blend for festive styling.', 'Kurta Sets', 'Festive Kurta Sets', 3290, 'Silk Blend', 'Wine', 'Festive', 4.3, 'https://source.unsplash.com/featured/900x1200/?festive+kurta+set&sig=127', 11),
('KST-FES-128', 'Occasion Festive Kurta Set', 'Occasion festive kurta set crafted in silk blend for festive styling.', 'Kurta Sets', 'Festive Kurta Sets', 3475, 'Silk Blend', 'Royal Blue', 'Festive', 4.5, 'https://source.unsplash.com/featured/900x1200/?festive+kurta+set&sig=128', 14),
('KST-FES-129', 'Gota Detail Festive Kurta Set', 'Gota Detail festive kurta set crafted in silk blend for festive styling.', 'Kurta Sets', 'Festive Kurta Sets', 3660, 'Silk Blend', 'Deep Green', 'Festive', 4.6, 'https://source.unsplash.com/featured/900x1200/?festive+kurta+set&sig=129', 17),
('KST-FES-130', 'Celebration Festive Kurta Set', 'Celebration festive kurta set crafted in silk blend for festive styling.', 'Kurta Sets', 'Festive Kurta Sets', 3845, 'Silk Blend', 'Rose Gold', 'Festive', 4.8, 'https://source.unsplash.com/featured/900x1200/?festive+kurta+set&sig=130', 20),
('KST-FES-131', 'Classic Festive Kurta Set', 'Classic festive kurta set crafted in silk blend for festive styling.', 'Kurta Sets', 'Festive Kurta Sets', 4030, 'Silk Blend', 'Magenta', 'Festive', 4.1, 'https://source.unsplash.com/featured/900x1200/?festive+kurta+set&sig=131', 23),
('KST-FES-132', 'Evening Festive Kurta Set', 'Evening festive kurta set crafted in silk blend for festive styling.', 'Kurta Sets', 'Festive Kurta Sets', 4215, 'Silk Blend', 'Amber', 'Festive', 4.3, 'https://source.unsplash.com/featured/900x1200/?festive+kurta+set&sig=132', 26),

-- KURTA SETS: Printed (6)
('KST-PRT-133', 'Floral Printed Kurta Set', 'Floral printed kurta set crafted in rayon for casual styling.', 'Kurta Sets', 'Printed Kurta Sets', 2490, 'Rayon', 'Berry', 'Casual', 4.5, 'https://source.unsplash.com/featured/900x1200/?printed+kurta+set&sig=133', 29),
('KST-PRT-134', 'Block Print Printed Kurta Set', 'Block Print printed kurta set crafted in rayon for casual styling.', 'Kurta Sets', 'Printed Kurta Sets', 2635, 'Rayon', 'Teal', 'Casual', 4.6, 'https://source.unsplash.com/featured/900x1200/?printed+kurta+set&sig=134', 32),
('KST-PRT-135', 'Weekend Printed Kurta Set', 'Weekend printed kurta set crafted in rayon for casual styling.', 'Kurta Sets', 'Printed Kurta Sets', 2780, 'Rayon', 'Peach', 'Casual', 4.8, 'https://source.unsplash.com/featured/900x1200/?printed+kurta+set&sig=135', 8),
('KST-PRT-136', 'Fusion Printed Kurta Set', 'Fusion printed kurta set crafted in rayon for casual styling.', 'Kurta Sets', 'Printed Kurta Sets', 2925, 'Rayon', 'Ivory', 'Casual', 4.1, 'https://source.unsplash.com/featured/900x1200/?printed+kurta+set&sig=136', 11),
('KST-PRT-137', 'Fresh Printed Kurta Set', 'Fresh printed kurta set crafted in rayon for casual styling.', 'Kurta Sets', 'Printed Kurta Sets', 3070, 'Rayon', 'Indigo', 'Casual', 4.3, 'https://source.unsplash.com/featured/900x1200/?printed+kurta+set&sig=137', 14),
('KST-PRT-138', 'Soft Drape Printed Kurta Set', 'Soft Drape printed kurta set crafted in rayon for casual styling.', 'Kurta Sets', 'Printed Kurta Sets', 3215, 'Rayon', 'Olive', 'Casual', 4.5, 'https://source.unsplash.com/featured/900x1200/?printed+kurta+set&sig=138', 17),

-- KURTA SETS: Chanderi (6)
('KST-CHN-139', 'Zari Trim Chanderi Kurta Set', 'Zari Trim chanderi kurta set crafted in chanderi for festive styling.', 'Kurta Sets', 'Chanderi Kurta Sets', 3590, 'Chanderi', 'Champagne', 'Festive', 4.6, 'https://source.unsplash.com/featured/900x1200/?chanderi+kurta+set&sig=139', 20),
('KST-CHN-140', 'Heritage Chanderi Kurta Set', 'Heritage chanderi kurta set crafted in chanderi for festive styling.', 'Kurta Sets', 'Chanderi Kurta Sets', 3780, 'Chanderi', 'Blush Pink', 'Festive', 4.8, 'https://source.unsplash.com/featured/900x1200/?chanderi+kurta+set&sig=140', 23),
('KST-CHN-141', 'Temple Border Chanderi Kurta Set', 'Temple Border chanderi kurta set crafted in chanderi for festive styling.', 'Kurta Sets', 'Chanderi Kurta Sets', 3970, 'Chanderi', 'Bottle Green', 'Festive', 4.1, 'https://source.unsplash.com/featured/900x1200/?chanderi+kurta+set&sig=141', 26),
('KST-CHN-142', 'Festive Chanderi Kurta Set', 'Festive chanderi kurta set crafted in chanderi for festive styling.', 'Kurta Sets', 'Chanderi Kurta Sets', 4160, 'Chanderi', 'Copper', 'Festive', 4.3, 'https://source.unsplash.com/featured/900x1200/?chanderi+kurta+set&sig=142', 29),
('KST-CHN-143', 'Elegant Chanderi Kurta Set', 'Elegant chanderi kurta set crafted in chanderi for festive styling.', 'Kurta Sets', 'Chanderi Kurta Sets', 4350, 'Chanderi', 'Plum', 'Festive', 4.5, 'https://source.unsplash.com/featured/900x1200/?chanderi+kurta+set&sig=143', 32),
('KST-CHN-144', 'Handcrafted Chanderi Kurta Set', 'Handcrafted chanderi kurta set crafted in chanderi for festive styling.', 'Kurta Sets', 'Chanderi Kurta Sets', 4540, 'Chanderi', 'Saffron', 'Festive', 4.6, 'https://source.unsplash.com/featured/900x1200/?chanderi+kurta+set&sig=144', 8),

-- KURTA SETS: Anarkali (6)
('KST-ANA-145', 'Flared Anarkali Kurta Set', 'Flared anarkali kurta set crafted in georgette blend for wedding styling.', 'Kurta Sets', 'Anarkali Kurta Sets', 3890, 'Georgette Blend', 'Maroon', 'Wedding', 4.8, 'https://source.unsplash.com/featured/900x1200/?anarkali+kurta+set&sig=145', 11),
('KST-ANA-146', 'Wedding Anarkali Kurta Set', 'Wedding anarkali kurta set crafted in georgette blend for wedding styling.', 'Kurta Sets', 'Anarkali Kurta Sets', 4100, 'Georgette Blend', 'Peach', 'Wedding', 4.1, 'https://source.unsplash.com/featured/900x1200/?anarkali+kurta+set&sig=146', 14),
('KST-ANA-147', 'Statement Anarkali Kurta Set', 'Statement anarkali kurta set crafted in georgette blend for wedding styling.', 'Kurta Sets', 'Anarkali Kurta Sets', 4310, 'Georgette Blend', 'Royal Blue', 'Wedding', 4.3, 'https://source.unsplash.com/featured/900x1200/?anarkali+kurta+set&sig=147', 17),
('KST-ANA-148', 'Twirl Anarkali Kurta Set', 'Twirl anarkali kurta set crafted in georgette blend for wedding styling.', 'Kurta Sets', 'Anarkali Kurta Sets', 4520, 'Georgette Blend', 'Wine', 'Wedding', 4.5, 'https://source.unsplash.com/featured/900x1200/?anarkali+kurta+set&sig=148', 20),
('KST-ANA-149', 'Graceful Anarkali Kurta Set', 'Graceful anarkali kurta set crafted in georgette blend for wedding styling.', 'Kurta Sets', 'Anarkali Kurta Sets', 4730, 'Georgette Blend', 'Emerald', 'Wedding', 4.6, 'https://source.unsplash.com/featured/900x1200/?anarkali+kurta+set&sig=149', 23),
('KST-ANA-150', 'Bridal Anarkali Kurta Set', 'Bridal anarkali kurta set crafted in georgette blend for wedding styling.', 'Kurta Sets', 'Anarkali Kurta Sets', 4940, 'Georgette Blend', 'Lilac', 'Wedding', 4.8, 'https://source.unsplash.com/featured/900x1200/?anarkali+kurta+set&sig=150', 26)

ON CONFLICT (product_id) DO NOTHING;
